[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F446RETx --probe 1366:0105"

[build]
rustflags = [
    "-Z", "emit-stack-sizes",

    "-C", "link-arg=-Tlink.x",
]

[env]
DEFMT_LOG = "debug"