[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs download --chip AT32F407VGT7 --probe 1366:0105"

[build]
rustflags = [
#    "-Z", "emit-stack-sizes",

    "-C", "link-arg=-Tlink.x",
]

[env]
DEFMT_LOG = "debug"