[package]
name = "cells_defs"
version = "0.1.0"
edition = "2021"

[dependencies]
emcell-macro = { path = "../emcell-macro" }
emcell = {path = "../emcell", features = ["rt-crate-cortex-m-rt"]}

[features]
default = []