[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip AT32F407VGT7 --probe 1366:0105"

[build]
target = "thumbv7em-none-eabihf"
rustflags = [
    "-Z", "emit-stack-sizes",

    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "debug"